[package]
name = "timetrack"
version = "0.3.0"
authors = ["Tomas Cernaj <tomas@cernaj.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.34.0"
