@startuml
skinparam monochrome true
skinparam shadowing false

[*] --> Idle
Idle --> DayTracking : on/clear tasks
Idle --> DayTracking : continue
Idle --> TaskActive : start

DayTracking --> Idle : off
DayTracking --> TaskActive : start

TaskActive --> TaskActive : start
TaskActive --> DayTracking : stop/persist stopwatch
TaskActive --> DayTracking : cancel

TaskActive --> Idle : off/persist stopwatch

TaskActive : entry/start stopwatch
TaskActive : exit/stop stopwatch

@enduml
