@startuml
skinparam monochrome true
skinparam shadowing false

[*] --> Idle
Idle --> DayTracking : on/clear tasks
Idle --> DayTracking : resume/persist pause timer
Idle --> TaskActive : start

DayTracking --> Idle : off/persist stopwatch\n start pause timer
DayTracking --> TaskActive : start

TaskActive --> TaskActive : start
TaskActive --> DayTracking : stop/persist stopwatch
TaskActive --> DayTracking : cancel

TaskActive --> Idle : off/persist stopwatch\n start pause timer

TaskActive : entry/start stopwatch
TaskActive : exit/stop stopwatch

@enduml
